//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoiceIdentification.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Activation
    {
        public int Id { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public string PhoneNumber { get; set; }
        [Required]
        [Remote("CheckExistingEmail", "Access", ErrorMessage = "Email already exists!")]
        public string EmailId { get; set; }
        public Nullable<System.Guid> IdentificationId { get; set; }
        public Nullable<System.Guid> VerificationId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
